const Character = require('./Character')
const Thief = require('./Thief')
const Mage = require('./Mage')
const Warrior = require('./Warrior')

const hero = new Character('Hero', 100, 15, 5)
const thief = new Thief('Thief', 80, 10, 3)
const mage = new Mage('Mage', 70, 12, 4, 20)
const warrior = new Warrior('Warrior', 120, 20, 8, 10)
hero.attack(thief)
thief.attack(hero)
mage.attack(hero)
mage.heal(hero)
warrior.attack(hero)
warrior.changeStance()
warrior.attack(hero)